## Creating virtual environments
syntax

``` python -m venv name-of-venv ```

## activate
``` source name-of-venv/bin/activate```

### incase activation fails, due to the error below, sol
error -> Running scripts disabled.

sol-> In your terminal, ``` Set-ExecutionPolicy RemoteSigned -scope CurrentUser```

In [ ]:
# importing pandas and numpy
import pandas as pd
import numpy as np #pip install numpy in terminal.


## core data structures
## series (1-dimensional)
A single column of data.

### Creating a series:
 ``` 
    import pandas as pd
    grades = pd.series([85, 90, 78, 92, 88])
```




In [2]:
grades = pd.Series([85, 90, 78, 92, 88])
print(grades)

0    85
1    90
2    78
3    92
4    88
dtype: int64


In [3]:
grades = pd.Series([85, 90, 78, 92, 88],
                   index=["Alice", "Bob", "Charlie", "Diana", "Eve"])
print(grades)

Alice      85
Bob        90
Charlie    78
Diana      92
Eve        88
dtype: int64


In [4]:
grades["Alice"] 

np.int64(85)

In [5]:
grades[["Alice", "Bob"]]

Alice    85
Bob      90
dtype: int64

## 2. DataFrame (2-dimensional)
This' a table with rows and columns

## Methods of creating a dataframe
1. Using a dict
2. Using a list of lists.


In [6]:
# method 1: From a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [24, 27, 22, 32],
    'City': ['Nairobi', 'Eldoret', 'Nakuru', 'Mombasa'],
    'Salary': [70000, 80000, 65000, 90000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age     City  Salary
0    Alice   24  Nairobi   70000
1      Bob   27  Eldoret   80000
2  Charlie   22   Nakuru   65000
3    Diana   32  Mombasa   90000


In [7]:
#method 2: From lists of lists.
data = [
    ['Alice', 24, 'Nairobi', 70000],
    ['Bob', 27, 'Eldoret', 80000],
    ['Charlie', 22, 'Nakuru', 65000],
    ['Diana', 32, 'Mombasa', 90000]
]
df = pd.DataFrame(data, columns= ['Name', 'Age', 'City', 'Salary'])
df


,Name,Age,City,Salary
0,Alice,24,Nairobi,70000
1,Bob,27,Eldoret,80000
2,Charlie,22,Nakuru,65000
3,Diana,32,Mombasa,90000


In [ ]:
# Reading csvs
df = pd.read_csv('auto-mpg.csv')
# df = pd.read_csv("filename.txt", sep='/t')
# df = pd.read_excel("filename.xlsx", sheet_name = ['Sales', 'Inventory'])
# salesdf = df['Sales']

# df = pd.read_json('data.json')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger


# inspecting data

In [ ]:
df.head() # returns the first 5 rows.

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino


In [ ]:
df.info() # Gives an overview of the df

<class 'pandas.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    int64  
 4   weight        392 non-null    int64  
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64  
 7   origin        392 non-null    int64  
 8   car name      392 non-null    str    
dtypes: float64(3), int64(5), str(1)
memory usage: 27.7 KB


In [ ]:
df.tail() # returns the last 5 rows. 

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
391,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10


In [ ]:
df.describe() # Gives a statistical summary but only has numeric values (columns)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,23.445918,5.471939,194.411990,104.469388,2977.584184,15.541327,75.979592,1.576531
std,7.805007,1.705783,104.644004,38.491160,849.402560,2.758864,3.683737,0.805518
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.000000,4.000000,105.000000,75.000000,2225.250000,13.775000,73.000000,1.000000
50%,22.750000,4.000000,151.000000,93.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,275.750000,126.000000,3614.750000,17.025000,79.000000,2.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000


In [ ]:
df.describe(include='all') # statistical summary but includes non-numeric values.

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,amc matador
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
mean,23.445918,5.471939,194.411990,104.469388,2977.584184,15.541327,75.979592,1.576531,NaN
std,7.805007,1.705783,104.644004,38.491160,849.402560,2.758864,3.683737,0.805518,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.000000,4.000000,105.000000,75.000000,2225.250000,13.775000,73.000000,1.000000,NaN
50%,22.750000,4.000000,151.000000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,275.750000,126.000000,3614.750000,17.025000,79.000000,2.000000,NaN


In [ ]:
#shape dimensions.
df.shape # returns the shape of the df ie number of rows by number of columns. 
df.shape[0] # returns just the number of rows.
df.shape[1] # returns just the number of columns.

9

In [25]:
# Column names
print(df.columns)

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='str')


In [ ]:
list(df.columns) # casting/ converting to a regular python list.

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model year',
 'origin',
 'car name']

In [ ]:
df.dtypes # returns the columns and their data types. 

mpg             float64
cylinders         int64
displacement    float64
horsepower        int64
weight            int64
acceleration    float64
model year        int64
origin            int64
car name            str
dtype: object

In [32]:
df.sample(2) # returns a no (specified) of random row(s)
df.sample(frac=1) # returns 5 % of the data (randomized as well)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
266,27.2,4,119.0,97,2300,14.7,78,3,datsun 510
322,40.8,4,85.0,65,2110,19.2,80,3,datsun 210
377,38.0,4,91.0,67,1965,15.0,82,3,honda civic
185,17.5,8,305.0,140,4215,13.0,76,1,chevrolet chevelle malibu classic
22,25.0,4,104.0,95,2375,17.5,70,2,saab 99e
...,...,...,...,...,...,...,...,...,...
310,37.2,4,86.0,65,2019,16.4,80,3,datsun 310
306,33.5,4,151.0,90,2556,13.2,79,1,pontiac phoenix
264,30.0,4,98.0,68,2155,16.5,78,1,chevrolet chevette
218,33.5,4,85.0,70,1945,16.8,77,3,datsun f-10 hatchback


## indexing and selection
### column selection
``` df['car name']```
or
``` df.mpg```
returns a series.

In [36]:
carName = df['car name']
carName

0      chevrolet chevelle malibu
1              buick skylark 320
2             plymouth satellite
3                  amc rebel sst
4                    ford torino
                 ...            
387              ford mustang gl
388                    vw pickup
389                dodge rampage
390                  ford ranger
391                   chevy s-10
Name: car name, Length: 392, dtype: str

### multiple columns
```df[["car name", "mpg"]]```

## row selection
### By position (iloc):
```df.iloc[0]``` 
The above returns the 1st row.

```df.iloc[0:2]```
The above returns the first 2 rows.

```df.iloc[[0, 2, 3, 391]]```
The above will return rows of index, 0, 2, 3 and 391.

In [41]:
df.iloc[1:3]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite


In [43]:
df.iloc[[0, 2, 3, 391]]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
391,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10


### selecting by label
```df.loc['chevy s-10']``` 
The above returns a row or rows with index "chevy s-10" if we had set index.

``` df.loc['dodge rampage':'chevy s-10']```
The above returns a range (inclusive)

#### setting index
we use ```.set_index("pass the column to use as index here")```


In [46]:
df_indexed = df.set_index('car name')
df_indexed

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
car name,,,,,,,,
chevrolet chevelle malibu,18.0,8,307.0,130,3504,12.0,70,1
buick skylark 320,15.0,8,350.0,165,3693,11.5,70,1
plymouth satellite,18.0,8,318.0,150,3436,11.0,70,1
amc rebel sst,16.0,8,304.0,150,3433,12.0,70,1
ford torino,17.0,8,302.0,140,3449,10.5,70,1
...,...,...,...,...,...,...,...,...
ford mustang gl,27.0,4,140.0,86,2790,15.6,82,1
vw pickup,44.0,4,97.0,52,2130,24.6,82,2
dodge rampage,32.0,4,135.0,84,2295,11.6,82,1


In [47]:
grades = pd.Series([85, 90, 78, 92, 88],
                   index=["Alice", "Bob", "Charlie", "Diana", "Eve"])
print(grades)

Alice      85
Bob        90
Charlie    78
Diana      92
Eve        88
dtype: int64


### row selection - short summary.
#### by position -> iloc (interger location)
```df.iloc[0]``` -> first row.
```df.iloc[0:2]``` -> first and second rows.
```df.iloc[[0, 2, 3]]``` -> specific rows by position.

#### by label -> loc
If you set index:
``` grades.loc['Alice']``` returns 85.

### specific cell selection:
#### using iloc
```df.iloc[0, 1]``` pass in the row then the column, row 0, column 1 in this case

#### using loc
``` df.loc[0, 'cylinders'] ``` picks row 0, column "cylinders"

In [48]:
grades.loc['Alice']

np.int64(85)

In [53]:
df.iloc[0,0]

np.float64(18.0)

In [57]:
df.loc[0, 'displacement']

np.float64(307.0)

In [51]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino


### differences between loc and iloc
iloc -> interger location/ position.
loc -> by label location.

In [61]:
df.loc[0:2, ['mpg', 'displacement']] #indexes, columns

,mpg,displacement
0,18.0,307.0
1,15.0,350.0
2,18.0,318.0


In [63]:
df.iloc[0:2, [0, 2]]

,mpg,displacement
0,18.0,307.0
1,15.0,350.0


# Slicing with conditions (boolean indexing)
## Basic condition.
#### Vehicles with mpg greater than 18.0
``` df[df['mpg'] > 18.0] ```
This will return all columns in the row where mpg is greater than 18.0

#### How it works.
step 1: df['mpg'] > 18.0 , returns a boolean value.

step 2: Boolean series to filter, only outputs on true rows.

In [72]:
(df[~(df['mpg'] > 18.0 )]).describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
count,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000
mean,14.991935,7.427419,316.548387,146.604839,3954.016129,13.721774,73.564516,1.048387
std,2.138216,1.005460,72.031650,36.204213,562.607908,2.645553,2.629544,0.250360
min,9.000000,3.000000,70.000000,72.000000,2124.000000,8.000000,70.000000,1.000000
25%,13.000000,6.000000,258.000000,120.000000,3552.250000,12.000000,71.750000,1.000000
50%,15.000000,8.000000,318.000000,150.000000,4054.500000,13.500000,73.000000,1.000000
75%,17.000000,8.000000,351.000000,170.000000,4360.750000,15.100000,75.250000,1.000000
max,18.000000,8.000000,455.000000,230.000000,5140.000000,21.000000,81.000000,3.000000


In [66]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,23.445918,5.471939,194.411990,104.469388,2977.584184,15.541327,75.979592,1.576531
std,7.805007,1.705783,104.644004,38.491160,849.402560,2.758864,3.683737,0.805518
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.000000,4.000000,105.000000,75.000000,2225.250000,13.775000,73.000000,1.000000
50%,22.750000,4.000000,151.000000,93.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,275.750000,126.000000,3614.750000,17.025000,79.000000,2.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000


### Multiple conditions.
#### AND (&)
``` df[(df['mpg'] > 18.0) & (df['cylinders'] == 6)]```

#### OR (|)

#### NOT (~)


In [70]:
(df[(df['mpg'] > 18.0) & (df['cylinders'] == 6)]).describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
count,52.000000,52.0,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,21.726923,6.0,210.480769,100.769231,3104.038462,15.938462,76.884615,1.250000
std,3.803616,0.0,32.028474,12.007539,303.026884,1.939593,3.329334,0.653047
min,18.100000,6.0,145.000000,76.000000,2472.000000,11.300000,70.000000,1.000000
25%,19.175000,6.0,198.000000,90.000000,2903.250000,15.000000,75.000000,1.000000
50%,20.550000,6.0,225.000000,100.000000,3077.500000,16.000000,77.500000,1.000000
75%,22.100000,6.0,232.000000,110.000000,3354.750000,17.200000,79.000000,1.000000
max,38.000000,6.0,262.000000,132.000000,3651.000000,19.600000,82.000000,3.000000


In [73]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino


In [75]:
# Using string conditions eg contains
(df[df['car name'].str.contains('chevrolet')]).describe(include='all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.0,43
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chevrolet impala
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
mean,20.472093,6.139535,237.860465,112.930233,3276.023256,15.320930,75.511628,1.0,NaN
std,6.182823,1.767180,103.859241,35.834537,806.333928,3.116741,3.647387,0.0,NaN
min,11.000000,4.000000,85.000000,52.000000,2035.000000,9.000000,70.000000,1.0,NaN
25%,15.250000,4.000000,140.000000,89.000000,2568.500000,13.000000,73.000000,1.0,NaN
50%,19.200000,6.000000,250.000000,105.000000,3336.000000,15.500000,75.000000,1.0,NaN
75%,26.000000,8.000000,307.000000,145.000000,3934.000000,17.150000,78.000000,1.0,NaN


### Sorting data
#### Basic sorting
#### Sort by using one column
Sorting using the horse power column
``` df.sort_values('horsepower')``` default sorts by ascending order

In [81]:
df.sort_values('horsepower', ascending= True)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
19,26.0,4,97.0,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
101,26.0,4,97.0,46,1950,21.0,73,2,volkswagen super beetle
324,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel)
323,44.3,4,90.0,48,2085,21.7,80,2,vw rabbit c (diesel)
242,43.1,4,90.0,48,1985,21.5,78,2,volkswagen rabbit custom diesel
...,...,...,...,...,...,...,...,...,...
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
94,12.0,8,455.0,225,4951,11.0,73,1,buick electra 225 custom
13,14.0,8,455.0,225,3086,10.0,70,1,buick estate wagon (sw)


#### sorting using multiple columns
Sort by horsepower and by acceleration.
``` df.sort_values(['horsepower', 'accelearation'], ascending=(True, False)) ```

In [82]:
df1 = df.sort_values(['horsepower', 'acceleration'], ascending=(True, False))
df1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
101,26.0,4,97.0,46,1950,21.0,73,2,volkswagen super beetle
19,26.0,4,97.0,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
324,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel)
323,44.3,4,90.0,48,2085,21.7,80,2,vw rabbit c (diesel)
242,43.1,4,90.0,48,1985,21.5,78,2,volkswagen rabbit custom diesel
...,...,...,...,...,...,...,...,...,...
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
94,12.0,8,455.0,225,4951,11.0,73,1,buick electra 225 custom
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
13,14.0,8,455.0,225,3086,10.0,70,1,buick estate wagon (sw)


#### In-place sorting.
Modify the original dataframe.
``` df.sort_values('mpg', inplace=True)```

In [84]:
df1.sort_values('mpg', inplace=True)
df1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20
66,11.0,8,429.0,208,4633,11.0,72,1,mercury marquis
123,11.0,8,350.0,180,3664,11.0,73,1,oldsmobile omega
...,...,...,...,...,...,...,...,...,...
324,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel)
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
323,44.3,4,90.0,48,2085,21.7,80,2,vw rabbit c (diesel)
327,44.6,4,91.0,67,1850,13.8,80,3,honda civic 1500 gl


In [86]:
df1 =df1.sort_values('mpg', ascending=False)
df1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
320,46.6,4,86.0,65,2110,17.9,80,3,mazda glc
327,44.6,4,91.0,67,1850,13.8,80,3,honda civic 1500 gl
323,44.3,4,90.0,48,2085,21.7,80,2,vw rabbit c (diesel)
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
324,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel)
...,...,...,...,...,...,...,...,...,...
123,11.0,8,350.0,180,3664,11.0,73,1,oldsmobile omega
66,11.0,8,429.0,208,4633,11.0,72,1,mercury marquis
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250


In [87]:
df1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
320,46.6,4,86.0,65,2110,17.9,80,3,mazda glc
327,44.6,4,91.0,67,1850,13.8,80,3,honda civic 1500 gl
323,44.3,4,90.0,48,2085,21.7,80,2,vw rabbit c (diesel)
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
324,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel)
...,...,...,...,...,...,...,...,...,...
123,11.0,8,350.0,180,3664,11.0,73,1,oldsmobile omega
66,11.0,8,429.0,208,4633,11.0,72,1,mercury marquis
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250


In [80]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino


## Renaming columns
### Rename methods.
#### Renaming specific columns:
``` df.rename(columns={'cylinders': 'no_of_cylinders', 'model year': 'YOM'}) ```

#### renaming all columns
Pass a list containing the new column names.
``` df.rename(columns = ["add columns here"])```

In [91]:
df.rename(columns={'cylinders': 'no_of_cylinders', 'model year': 'YOM'}, inplace=True)
df


,mpg,no_of_cylinders,displacement,horsepower,weight,acceleration,YOM,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger


#### using functions.
#### making all column names lowercase
```df.columns = df.columns.str.lower()```

#### removing spaces
```df.columns = df.columns.str.replace(' ', '_')```

#### both at once
``` df.columns = df.columns.str.lower().str.replace(' ', '_')```

#### Always clean column names early. No spaces, lowercase, use underscores. Will make your work so much easier later.


In [93]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df

,mpg,no_of_cylinders,displacement,horsepower,weight,acceleration,yom,origin,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger


## Adding and deleting columns.
### Adding columns. 
Adding a column syntax:
``` df['column_name'] = 'value'```

In [94]:
df['country'] = 'USA'
df

,mpg,no_of_cylinders,displacement,horsepower,weight,acceleration,yom,origin,car_name,country
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,USA
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,USA
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,USA
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,USA
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,USA
...,...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl,USA
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup,USA
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage,USA
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger,USA


In [96]:
grades.info()

<class 'pandas.Series'>
Index: 5 entries, Alice to Eve
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 252.0+ bytes


In [97]:
grades = pd.DataFrame([85, 90, 78, 92, 88],
                   index=["Alice", "Bob", "Charlie", "Diana", "Eve"])
print(grades)

          0
Alice    85
Bob      90
Charlie  78
Diana    92
Eve      88


In [105]:
grades.rename(columns={'mark':'marks'}, inplace=True)
grades


,marks
Alice,85
Bob,90
Charlie,78
Diana,92
Eve,88


#### adding columns from a calculation.

In [106]:

grades['new_marks'] = grades['marks'] - 5
grades

,marks,new_marks
Alice,85,80
Bob,90,85
Charlie,78,73
Diana,92,87
Eve,88,83


### adding columns based on a condition.
Use np.where (This behaves just like if)

``` 
    import numpy as np 
    grades['grade'] = np.where(grades['new_marks'] > 85, 'Pass', 'Fail')
```

Using pandas where
``` 
    grades['grade'] = grades['new_marks'].apply(
    lambda x: 'Pass' if x > 85 else 'Fail'
)
```

In [108]:
import numpy as np 
grades['grade'] = np.where(grades['new_marks'] > 85, 'Pass', 'Fail')
grades

,marks,new_marks,grade
Alice,85,80,Fail
Bob,90,85,Fail
Charlie,78,73,Fail
Diana,92,87,Pass
Eve,88,83,Fail


In [110]:
grades['grade_using_pandas'] = grades['new_marks'].apply(
    lambda x: 'Pass' if x > 85 else 'Fail'
)
grades


,marks,new_marks,grade,grade_using_pandas
Alice,85,80,Fail,Fail
Bob,90,85,Fail,Fail
Charlie,78,73,Fail,Fail
Diana,92,87,Pass,Pass
Eve,88,83,Fail,Fail


#### deleting columns
we use .drop() or keyword del.


In [ ]:
# example using .drop()
grades.drop(columns= ['grade'], inplace= True)
grades

,marks,new_marks,grade_using_pandas
Alice,85,80,Fail
Bob,90,85,Fail
Charlie,78,73,Fail
Diana,92,87,Pass
Eve,88,83,Fail


In [113]:
# example using del
del grades['grade_using_pandas']
grades

,marks,new_marks
Alice,85,80
Bob,90,85
Charlie,78,73
Diana,92,87
Eve,88,83


# data cleaning and analysis

### Handling missing data.
Finding or detecting missing values.

``` df.isnull() ```
returns a dataframe of True/False, True where we have a missing value.

``` df.isnull().sum() ```
returns count of missing values per column. Takes True as 1 and False as 0.

``` df.isnull().sum().sum() ``` 
returns the total missing values in a given dataframe.

``` (df.isnull().sum().sum())/len(df)```
returns percentage missing.


In [117]:
# checking for missing values.
(df.isnull().sum().sum())/len(df) #

np.float64(0.0)

In [118]:
grades

,marks,new_marks
Alice,85,80
Bob,90,85
Charlie,78,73
Diana,92,87
Eve,88,83


In [121]:
housing_data = pd.read_csv("housing_prices.csv")
housing_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   str    
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   str    
 6   Alley          91 non-null     str    
 7   LotShape       1460 non-null   str    
 8   LandContour    1460 non-null   str    
 9   Utilities      1460 non-null   str    
 10  LotConfig      1460 non-null   str    
 11  LandSlope      1460 non-null   str    
 12  Neighborhood   1460 non-null   str    
 13  Condition1     1460 non-null   str    
 14  Condition2     1460 non-null   str    
 15  BldgType       1460 non-null   str    
 16  HouseStyle     1460 non-null   str    
 17  OverallQual    1460 non-null   int64  
 18  OverallCond    1460

### filling rows with missing values
#### filling with a specific value
``` housing_data['LotFrontage'].fillna(0) ```
will filling the missing values with 0

``` housing_data['LotFrontage'].fillna(housing_data['LotFrontage].median()) ```
will fill missing values with median (Better for outliers)

In [128]:
hd = housing_data['LotFrontage'].fillna(0)
hd.describe()

count    1460.000000
mean       57.623288
std        34.664304
min         0.000000
25%        42.000000
50%        63.000000
75%        79.000000
max       313.000000
Name: LotFrontage, dtype: float64

In [129]:
housing_data['LotFrontage'].describe()

count    1201.000000
mean       70.049958
std        24.284752
min        21.000000
25%        59.000000
50%        69.000000
75%        80.000000
max       313.000000
Name: LotFrontage, dtype: float64

In [132]:
median = housing_data['LotFrontage'].median()

hd2 = housing_data['LotFrontage'].fillna(median)
hd2.describe()

count    1460.000000
mean       69.863699
std        22.027677
min        21.000000
25%        60.000000
50%        69.000000
75%        79.000000
max       313.000000
Name: LotFrontage, dtype: float64

In [ ]:
hd3 = housing_data['Alley'].fillna('UNKNOWN')
hd3.describe(include='all') 
# but we should drop not replace as this column is missing more than 50% of the data

count        1460
unique          3
top       UNKNOWN
freq         1369
Name: Alley, dtype: object

## Handling duplicates
### Detecting duplicates.
``` df.duplicated() ```
returns a boolean series, True/ False.

``` df[df.duplicated()] ```
shows the duplicated rows

In [146]:
df_duplicate = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Alice', 'Charlie'],
    'Age': [25, 30, 25, 35],
    'city': ['Nairobi', 'Kisumu', 'Nairobi', 'Mombasa']
})

In [144]:
print("Before:", len(df_duplicate))
df_duplicate = df_duplicate.drop_duplicates()
print("After: ", len(df_duplicate))

Before: 4
After:  3


In [145]:
df_duplicate

,name,Age,city
0,Alice,25,Nairobi
1,Bob,30,Kisumu
3,Charlie,35,Mombasa


In [147]:
df_duplicate.drop_duplicates(keep=False)

,name,Age,city
1,Bob,30,Kisumu
3,Charlie,35,Mombasa


### Changing data types
#### checking data types
``` df['Age'].dtype```

``` df.dtypes ```
``` df.info() ```

#### converting data types
#### basic conversion
``` df['Age'].astype(int) ```
converts age column to interger.

#### converting to date
``` df['date'] = pd.to_datetime(df['date']) ```

#### converting to category (category is memory efficient)
``` df['city'] = df['city'].astype('category') ```

In [149]:
df_duplicate.dtypes

name      str
Age     int64
city      str
dtype: object

In [152]:
print ((df_duplicate['Age'].astype(str)).dtypes)

str


In [154]:
df_duplicate['city'] = df_duplicate['city'].astype('category')
df_duplicate.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   name    4 non-null      str     
 1   Age     4 non-null      int64   
 2   city    4 non-null      category
dtypes: category(1), int64(1), str(1)
memory usage: 224.0 bytes


In [155]:
print(df_duplicate.memory_usage(deep=True))

Index    132
name     216
Age       32
city     171
dtype: int64


In [156]:
df_duplicat = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Alice', 'Charlie'],
    'Age': [25, 30, 25, 35],
    'city': ['Nairobi', 'Kisumu', 'Nairobi', 'Mombasa']
})
print(df_duplicat.memory_usage(deep=True))

Index    132
name     216
Age       32
city     223
dtype: int64
